"""
IT Incident Triage Assistant - API (Step 2)

Wraps the existing triage_ticket() function from triage.py in a small
web API, so it can be called over HTTP instead of only from the command line.

Setup: same environment variables as triage.py (AWS_ACCESS_KEY_ID,
AWS_SECRET_ACCESS_KEY, AWS_REGION), plus:
    pip install fastapi "uvicorn[standard]"

Run:
    uvicorn api:app --reload

Then visit http://127.0.0.1:8000/docs for an interactive test page,
auto-generated by FastAPI from the code below.
"""

from fastapi import FastAPI
from pydantic import BaseModel

from triage import triage_ticket

app = FastAPI(
    title="IT Incident Triage Assistant",
    description="Classifies IT support tickets using Claude on AWS Bedrock, with RAG over past resolution notes.",
    version="1.0.0",
)


# Pydantic models define the exact shape of data coming in and going out.
# FastAPI uses these to validate requests automatically and to generate
# the interactive docs page for free.
class TicketRequest(BaseModel):
    description: str


class TriageResponse(BaseModel):
    is_valid_ticket: bool
    category: str
    priority: str
    confidence: float
    suggested_first_step: str
    referenced_past_case: str | None = None
    reasoning: str


@app.get("/")
def health_check():
    """Simple endpoint to confirm the API is running."""
    return {"status": "ok", "service": "IT Incident Triage Assistant"}


@app.post("/triage", response_model=TriageResponse)
def triage_endpoint(ticket: TicketRequest):
    """Accepts a ticket description and returns the AI-generated triage result."""
    result = triage_ticket(ticket.description)
    return result
